# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ haskellPackages ? (import <nixpkgs> {}).haskellPackages }:
let
    inherit (haskellPackages) cabal alex cpphs filepath HUnit mtl parsec QuickCheck syb testFramework testFrameworkHunit testFrameworkQuickcheck2 lens;
in cabal.mkDerivation (self: {
  pname = "language-java";
  version = "0.2.7";
  src = ./.;
  buildDepends = [ cpphs parsec syb lens ];
  testDepends = [
    filepath HUnit mtl QuickCheck testFramework testFrameworkHunit
    testFrameworkQuickcheck2
  ];
  buildTools = [ alex ];
  meta = {
    homepage = "http://github.com/vincenthz/language-java";
    description = "Manipulating Java source: abstract syntax, lexer, parser, and pretty-printer";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
